version: '3.5'

services:
  postgres:
    container_name: gcp_reproducer
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"